name: "Release Poetry Python Project"
description: "Release a Poetry Python project using semantic-release"
branding:
  icon: upload-cloud
  color: blue

inputs:
  python-version:
    description: "Python version. If not set, Python will not be setup automatically."
    required: false
  poetry-version:
    description: "Poetry version. If not set, poetry will not be setup automatically."
    required: false
  pypi-token:
    description: "PyPI token. If not set, we will not publish the package."
    required: false
  github-token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}

outputs:
  released:
    description: New version released
    value: ${{ steps.semantic-release.outputs.new_release_published }}
  version:
    description: Version
    value: ${{ steps.semantic-release.outputs.new_release_version }}
  major:
    description: Major version
    value: ${{ steps.semantic-release.outputs.new_release_major_version }}
  minor:
    description: Minor version
    value: ${{ steps.semantic-release.outputs.new_release_minor_version }}
  patch:
    description: Patch version
    value: ${{ steps.semantic-release.outputs.new_release_patch_version }}
  channel:
    description: Release channel
    value: ${{ steps.semantic-release.outputs.new_release_channel }}
  release-notes:
    description: Release notes
    value: ${{ steps.semantic-release.outputs.new_release_notes }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      if: ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.python-version }}"
    - name: Setup Poetry
      if: ${{ inputs.poetry-version }}
      shell: sh
      run: "pip install poetry==${{ inputs.poetry-version }}"
    - name: Get semantic-release version
      shell: sh
      id: semantic-release-version
      run: "echo version=$(npm view @cihelper/semanticrelease-preset-poetry dependencies.semantic-release) >> $GITHUB_OUTPUT"
    - name: Run semantic-release
      id: semantic-release
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PYPI_TOKEN: ${{ inputs.pypi-token }}
      with:
        semantic_version: ${{ steps.semantic-release-version.outputs.version }}
        extra_plugins: "@cihelper/semanticrelease-preset-poetry@1"
        extends: "@cihelper/semanticrelease-preset-poetry"
